name: bash
on: 
  push:
    branches: [dev]

jobs:
  checkout:
    if: github.repository == 'ydh-action/github-actions'
    runs-on: ubuntu-latest
    steps: 
    - name: checkout the code
      uses: actions/checkout@v4
    - name: run bash  
      run: | 
        chmod +x password-period.sh
        ./password-period.sh

