#트리거 구성  
name: cicd-01
on:
  pull_request: 
    types: [opened, synchronize, closed]
    branches: [dev]
    paths:
    - 'my-app/**'

#job 구성
jobs:
  test:
  if: github.event.action == 'opened' || github.event.action == 'synchronize'
  runs-on: ubuntu-latest
  steps:
  - name: checkout
    uses: actions/checkout@v4

  image-build:
  if: github.event.pull_request merged == true
  runs-on: ubuntu-latest
  steps:
  - name: checkout
    uses: actions/checkout@v4 

  deploy:
    runs-on: ubuntu-latest
    needs: [image-build]
    steps:
    - name: checkout
      uses: actions/checkout@v4