name: test-local
on: 
  push:
    branches: [dev]
    
jobs:
  test:
    if: github.repository == 'ydh-action/github-actions'
    runs-on: ubuntu-latest
    steps:
    - name: checout the code
      uses: actions/checkout@v4
  
  image-build:
    runs-on: ubuntu-latest
    needs: [test]
    steps: 
    - name: docker build
      run: | 
        docker login docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWD }}
        docker pull dockerydh/custom-ubuntu:yoon
        pwd
  
  deploy: 
    runs-on: ubuntu-latest
    needs: [image-build]
    steps: 
    - name: image deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CINAMON_HOST }}
        username: ${{ secrets.CINAMON_USERNAME }}
        key: ${{ secrets.CINAMON_SERVERKEY }}
        port: ${{ secrets.PORT }}
        script: |
          whoami
                   
          

  
        