name: test-local
on: 
  push:
    branches: [dev]
    
jobs:
  test:
    if: github.repository == 'ydh-action/github-actions'
    runs-on: ubuntu-latest
    steps:
    - name: checout the code
      uses: actions/checkout@v4

    - name: Create SSH Key
      run: |
        echo "${{ secrets.CINAMON_SERVERKEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: Create SSH directory 
      run: | 
        mkdir -p ~/.ssh
    - name: Add known host 
      run: |
        ssh-keyscan ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
  
  image-build:
    runs-on: ubuntu-latest
    needs: [test]
    steps: 
    - name: docker build
      run: | 
        docker login docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWD }}
        docker pull dockerydh/custom-ubuntu:yoon
        pwd
        whoami
  
  #deploy: 
  # runs-on: ubuntu-latest
  # needs: [image-build]
  # steps: 
  # - name: image deploy
  #   uses: appleboy/ssh-action@master
  #   with:
  #     host: ${{ secrets.CINAMON_HOST }}
  #     username: ${{ secrets.CINAMON_USERNAME }}
  #     key: ${{ secrets.CINAMON_SERVERKEY }}
  #     port: ${{ secrets.PORT }}
  #     script: |
  #       whoami
                   
          

  
        