name: test-ssh
on: 
  push:
    branches: [dev]
    
jobs:
  test:
    if: github.repository == 'ydh-action/github-actions'
    runs-on: ubuntu-latest
    steps:
    - name: checout the code
      uses: actions/checkout@v4
  
  ssh: 
   runs-on: ubuntu-latest
   needs: [test]
   steps: 
   - name: image deploy
     uses: appleboy/ssh-action@v0.1.4
     with:
       host: ${{ secrets.CINAMON_HOST }}
       username: ${{ secrets.CINAMON_USERNAME }}
       key: ${{ secrets.CINAMON_SERVERKEY }}
       port: ${{ secrets.PORT }}
       script: |
        echo "테스트 출력"
                   
          

  
        